# Docker compose for the distributed systems course @2017
version: '2'

services:
  java:
    build: ./docker/java
    image: sd/java
    container_name: sd_java
    volumes_from:
      - code
      - code-server
    volumes:
      - ./app/sd2017:/opt/sd
      - ./app/web:/usr/local/tomcat/webapps

  tomcat:
    build: ./docker/tomcat
    image: sd/tomcat
    container_name: sd_tomcat
    volumes_from:
      - code-server
    volumes:
      - ./app/web:/usr/local/tomcat/webapps
      - ./docker/tomcat/conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    ports:
      - 9090:8080

  mysql:
    build: ./docker/mysql
    image: sd/mysql5.7
    container_name: sd_mysql5.7
    volumes_from:
      - dbdata-mysql
    volumes:
      - ./docker/database/mysql/data:/var/lib/mysql
      - ./docker/mysql/setup:/docker-entrypoint-initdb.d
    links:
      - dbdata-mysql
    ports:
      - 3306
    env_file:
      - ./docker/mysql/.env

  sql-server:
    build: ./docker/sql-server
    image: sd/sql-server
    container_name: sd_sql_server
    volumes_from:
      - dbdata-sqlserver
    volumes:
      - ./docker/database/sql-server/data:/var/opt/mssql
      - ./docker/database/sql-server/setup:/docker-entrypoint-initdb.d
      - ./docker/sql-server/setup:/usr/src/setup
      - ./docker/sql-server/bin:/usr/local/bin
      - ./docker/sql-server/data:/usr/src/data
    links:
      - dbdata-sqlserver
    ports:
      - 1433
    env_file:
      - ./docker/sql-server/.env

  postgresql:
    build: ./docker/postgresql
    image: sd/postgresql
    container_name: sd_postgresql
    volumes_from:
      - dbdata-postgresql
    volumes:
      - ./docker/database/postgresql/data:/var/lib/postgresql/data
      - ./docker/database/postgresql/setup:/docker-entrypoint-initdb.d
      - ./docker/postgresql/setup:/usr/src/setup
      - ./docker/postgresql/bin:/usr/local/bin
      - ./docker/postgresql/data:/usr/src/data
    links:
      - dbdata-postgresql
    ports:
      - 5432
    env_file:
      - ./docker/postgresql/.env

  phpmyadmin:
    build: ./docker/phpmyadmin
    image: sd/phpmyadmin
    container_name: sd_phpmyadmin
    volumes_from:
      - dbdata-mysql
    ports:
      - 80
    env_file:
      - ./docker/phpmyadmin/.env

  dbdata-mysql:
    image: tianon/true
    container_name: sd_dbdata_mysql
    volumes:
      - /var/lib/mysql

  dbdata-postgresql:
    image: tianon/true
    container_name: sd_dbdata_postgresql
    volumes:
      - /var/lib/postgresql/data

  dbdata-sqlserver:
    image: tianon/true
    container_name: sd_dbdata_sqlserver
    volumes:
      - /var/opt/mssql

  code:
    image: tianon/true
    container_name: sd_code
    volumes:
      - ./app/sd2017:/opt/sd

  code-server:
    image: tianon/true
    container_name: sd_code_server
    volumes:
      - ./app/web:/usr/local/tomcat/webapps